import {
  SettingCategory,
  SettingDataType,
} from '../../generated/prisma/client';

export type SettingDefinition = {
  key: string;
  category: SettingCategory;
  dataType: SettingDataType;
  description: string;
  defaultValue: string;
  isSensitive?: boolean;
  isPublic?: boolean;
};

const numbering = (
  key: string,
  prefix: string,
  description: string,
): SettingDefinition => ({
  key,
  category: SettingCategory.NUMBERING,
  dataType: SettingDataType.JSON,
  description,
  defaultValue: JSON.stringify({
    prefix,
    separator: '-',
    includeYear: true,
    includeMonth: false,
    sequenceLength: 4,
    resetYearly: false,
    resetMonthly: false,
  }),
});

export const SETTINGS_CATALOG: SettingDefinition[] = [
  // Business
  {
    key: 'business.name',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Hotel / business name',
    defaultValue: 'Casa Bella',
    isPublic: true,
  },
  {
    key: 'business.shortName',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Short business name',
    defaultValue: 'Casa Bella',
    isPublic: true,
  },
  {
    key: 'business.address',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Business address',
    defaultValue: '',
    isPublic: true,
  },
  {
    key: 'business.city',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'City',
    defaultValue: '',
    isPublic: true,
  },
  {
    key: 'business.phone',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Primary phone',
    defaultValue: '',
    isPublic: true,
  },
  {
    key: 'business.alternatePhone',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Alternate phone',
    defaultValue: '',
  },
  {
    key: 'business.email',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Business email',
    defaultValue: '',
    isPublic: true,
  },
  {
    key: 'business.website',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Website URL',
    defaultValue: '',
    isPublic: true,
  },
  {
    key: 'business.taxNumber',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Tax / registration number',
    defaultValue: '',
  },
  {
    key: 'business.logoUrl',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Logo URL',
    defaultValue: '',
    isPublic: true,
  },
  {
    key: 'business.receiptFooter',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Receipt footer text',
    defaultValue: 'Thank you for staying with us.',
  },
  {
    key: 'business.invoiceFooter',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Invoice footer text',
    defaultValue: '',
  },
  {
    key: 'business.termsAndConditions',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Terms and conditions',
    defaultValue: '',
  },
  {
    key: 'business.timezone',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Default timezone',
    defaultValue: 'Asia/Karachi',
    isPublic: true,
  },
  {
    key: 'business.dateFormat',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Default date format',
    defaultValue: 'DD/MM/YYYY',
    isPublic: true,
  },
  {
    key: 'business.timeFormat',
    category: SettingCategory.BUSINESS,
    dataType: SettingDataType.STRING,
    description: 'Default time format',
    defaultValue: 'HH:mm',
    isPublic: true,
  },

  // Finance
  {
    key: 'finance.currency',
    category: SettingCategory.FINANCE,
    dataType: SettingDataType.STRING,
    description: 'Currency code',
    defaultValue: 'PKR',
    isPublic: true,
  },
  {
    key: 'finance.currencySymbol',
    category: SettingCategory.FINANCE,
    dataType: SettingDataType.STRING,
    description: 'Currency symbol',
    defaultValue: 'Rs',
    isPublic: true,
  },
  {
    key: 'finance.decimalPlaces',
    category: SettingCategory.FINANCE,
    dataType: SettingDataType.NUMBER,
    description: 'Decimal places for money',
    defaultValue: '2',
    isPublic: true,
  },
  {
    key: 'finance.defaultServiceCharge',
    category: SettingCategory.FINANCE,
    dataType: SettingDataType.NUMBER,
    description: 'Default service charge percentage',
    defaultValue: '0',
  },
  {
    key: 'finance.defaultTaxPercentage',
    category: SettingCategory.FINANCE,
    dataType: SettingDataType.NUMBER,
    description: 'Default tax percentage',
    defaultValue: '0',
  },
  {
    key: 'finance.defaultSecurityDeposit',
    category: SettingCategory.FINANCE,
    dataType: SettingDataType.NUMBER,
    description: 'Default security deposit amount',
    defaultValue: '0',
  },
  {
    key: 'finance.expenseApprovalThreshold',
    category: SettingCategory.FINANCE,
    dataType: SettingDataType.NUMBER,
    description: 'Expense approval threshold',
    defaultValue: '50000',
    isSensitive: true,
  },
  {
    key: 'finance.discountApprovalThreshold',
    category: SettingCategory.FINANCE,
    dataType: SettingDataType.NUMBER,
    description: 'Discount approval threshold',
    defaultValue: '1000',
    isSensitive: true,
  },
  {
    key: 'finance.refundApprovalThreshold',
    category: SettingCategory.FINANCE,
    dataType: SettingDataType.NUMBER,
    description: 'Refund approval threshold',
    defaultValue: '0',
    isSensitive: true,
  },
  {
    key: 'finance.allowOverpayment',
    category: SettingCategory.FINANCE,
    dataType: SettingDataType.BOOLEAN,
    description: 'Allow overpayment',
    defaultValue: 'true',
  },
  {
    key: 'finance.allowPartialPayment',
    category: SettingCategory.FINANCE,
    dataType: SettingDataType.BOOLEAN,
    description: 'Allow partial payment',
    defaultValue: 'true',
  },
  {
    key: 'finance.allowPaymentAdjustment',
    category: SettingCategory.FINANCE,
    dataType: SettingDataType.BOOLEAN,
    description: 'Allow payment adjustment',
    defaultValue: 'true',
  },

  // Electricity
  {
    key: 'electricity.ratePerUnit',
    category: SettingCategory.ELECTRICITY,
    dataType: SettingDataType.NUMBER,
    description: 'Default electricity rate per unit (PKR)',
    defaultValue: '95',
  },
  {
    key: 'electricity.allowDuplicateOverride',
    category: SettingCategory.ELECTRICITY,
    dataType: SettingDataType.BOOLEAN,
    description: 'Allow duplicate electricity reading override',
    defaultValue: 'false',
    isSensitive: true,
  },

  // Numbering
  numbering('numbering.booking', 'BK', 'Booking number format'),
  numbering('numbering.payment', 'PAY', 'Payment number format'),
  numbering('numbering.expense', 'EXP', 'Expense number format'),
  numbering('numbering.ownerPayment', 'OWP', 'Owner payment number format'),
  numbering('numbering.employee', 'EMP', 'Employee number format'),
  numbering('numbering.inventoryItem', 'INV', 'Inventory item number format'),
  numbering(
    'numbering.inventoryMovement',
    'MOV',
    'Inventory movement number format',
  ),
  numbering('numbering.roomAsset', 'AST', 'Room asset number format'),
  numbering('numbering.approval', 'APR', 'Approval request number format'),
  {
    key: 'numbering.receipt',
    category: SettingCategory.NUMBERING,
    dataType: SettingDataType.JSON,
    description: 'Receipt number format',
    defaultValue: JSON.stringify({
      prefix: 'RC',
      separator: '-',
      includeYear: true,
      includeMonth: false,
      sequenceLength: 6,
      resetYearly: true,
      resetMonthly: false,
    }),
  },
  numbering('numbering.invoice', 'INVOC', 'Invoice number format'),
  numbering('numbering.backup', 'BKP', 'Backup number format'),

  // Dashboard colors
  {
    key: 'dashboard.colors',
    category: SettingCategory.DASHBOARD,
    dataType: SettingDataType.JSON,
    description: 'Room status display colors',
    defaultValue: JSON.stringify({
      AVAILABLE: '#22c55e',
      OCCUPIED: '#3b82f6',
      OCCUPIED_DAILY: '#9333ea',
      CLEANING_REQUIRED: '#ef4444',
      MONTHLY_TENANT_VACANT: '#f5f5f5',
      MAINTENANCE: '#9ca3af',
      BLOCKED: '#000000',
    }),
    isPublic: true,
  },

  // Booking
  {
    key: 'booking.defaultCheckInTime',
    category: SettingCategory.BOOKING,
    dataType: SettingDataType.STRING,
    description: 'Default check-in time',
    defaultValue: '14:00',
  },
  {
    key: 'booking.defaultCheckOutTime',
    category: SettingCategory.BOOKING,
    dataType: SettingDataType.STRING,
    description: 'Default check-out time',
    defaultValue: '12:00',
  },
  {
    key: 'booking.allowHourly',
    category: SettingCategory.BOOKING,
    dataType: SettingDataType.BOOLEAN,
    description: 'Allow hourly booking',
    defaultValue: 'true',
  },
  {
    key: 'booking.allowDaily',
    category: SettingCategory.BOOKING,
    dataType: SettingDataType.BOOLEAN,
    description: 'Allow daily booking',
    defaultValue: 'true',
  },
  {
    key: 'booking.minimumHourlyDuration',
    category: SettingCategory.BOOKING,
    dataType: SettingDataType.NUMBER,
    description: 'Minimum hourly duration',
    defaultValue: '1',
  },
  {
    key: 'booking.minimumDailyDuration',
    category: SettingCategory.BOOKING,
    dataType: SettingDataType.NUMBER,
    description: 'Minimum daily duration',
    defaultValue: '1',
  },
  {
    key: 'booking.allowOverlapOverride',
    category: SettingCategory.BOOKING,
    dataType: SettingDataType.BOOLEAN,
    description: 'Allow booking overlap override',
    defaultValue: 'false',
    isSensitive: true,
  },
  {
    key: 'booking.requireGuestId',
    category: SettingCategory.BOOKING,
    dataType: SettingDataType.BOOLEAN,
    description: 'Require guest CNIC/passport',
    defaultValue: 'true',
  },
  {
    key: 'booking.requirePaymentBeforeCheckIn',
    category: SettingCategory.BOOKING,
    dataType: SettingDataType.BOOLEAN,
    description: 'Require payment before check-in',
    defaultValue: 'false',
  },
  {
    key: 'booking.defaultSource',
    category: SettingCategory.BOOKING,
    dataType: SettingDataType.STRING,
    description: 'Default booking source',
    defaultValue: 'WALK_IN',
  },
  {
    key: 'booking.checkoutGracePeriodMinutes',
    category: SettingCategory.BOOKING,
    dataType: SettingDataType.NUMBER,
    description: 'Checkout grace period in minutes',
    defaultValue: '60',
  },
  {
    key: 'booking.autoNoShowHours',
    category: SettingCategory.BOOKING,
    dataType: SettingDataType.NUMBER,
    description: 'Auto mark no-show after hours',
    defaultValue: '0',
  },

  // Payment
  {
    key: 'payment.enabledMethods',
    category: SettingCategory.PAYMENT,
    dataType: SettingDataType.JSON,
    description: 'Enabled payment methods',
    defaultValue: JSON.stringify([
      'CASH',
      'BANK_TRANSFER',
      'CARD',
      'EASYPAISA',
      'JAZZCASH',
      'OTHER',
    ]),
  },
  {
    key: 'payment.defaultMethod',
    category: SettingCategory.PAYMENT,
    dataType: SettingDataType.STRING,
    description: 'Default payment method',
    defaultValue: 'CASH',
  },
  {
    key: 'payment.refundApprovalRequired',
    category: SettingCategory.PAYMENT,
    dataType: SettingDataType.BOOLEAN,
    description: 'Refund approval required',
    defaultValue: 'true',
    isSensitive: true,
  },
  {
    key: 'payment.reversalApprovalRequired',
    category: SettingCategory.PAYMENT,
    dataType: SettingDataType.BOOLEAN,
    description: 'Reversal approval required',
    defaultValue: 'true',
    isSensitive: true,
  },
  {
    key: 'payment.allowAdvance',
    category: SettingCategory.PAYMENT,
    dataType: SettingDataType.BOOLEAN,
    description: 'Allow advance payments',
    defaultValue: 'true',
  },
  {
    key: 'payment.allowHalfPayments',
    category: SettingCategory.PAYMENT,
    dataType: SettingDataType.BOOLEAN,
    description: 'Allow half payments',
    defaultValue: 'true',
  },
  {
    key: 'payment.requireTxnRefForNonCash',
    category: SettingCategory.PAYMENT,
    dataType: SettingDataType.BOOLEAN,
    description: 'Require transaction reference for non-cash',
    defaultValue: 'false',
  },
  {
    key: 'payment.proofRequiredAboveAmount',
    category: SettingCategory.PAYMENT,
    dataType: SettingDataType.NUMBER,
    description: 'Require proof attachment above amount',
    defaultValue: '0',
  },
  {
    key: 'payment.bankAccountName',
    category: SettingCategory.PAYMENT,
    dataType: SettingDataType.STRING,
    description: 'Public bank account name for website transfers',
    defaultValue: 'CASA BELLA',
    isPublic: true,
  },
  {
    key: 'payment.bankIban',
    category: SettingCategory.PAYMENT,
    dataType: SettingDataType.STRING,
    description: 'Public IBAN for website bank transfers',
    defaultValue: 'PK60FAYS3203301000003409',
    isPublic: true,
  },
  {
    key: 'payment.bankBranch',
    category: SettingCategory.PAYMENT,
    dataType: SettingDataType.STRING,
    description: 'Public bank branch for website transfers',
    defaultValue: 'IBB E-11, ISLAMABAD',
    isPublic: true,
  },
  {
    key: 'payment.bankInstructions',
    category: SettingCategory.PAYMENT,
    dataType: SettingDataType.STRING,
    description: 'Customer instructions for bank transfer',
    defaultValue:
      'Please transfer the selected amount to the Casa Bella bank account using the details provided. After completing the transfer, submit your transaction details. Our team will verify your payment against our bank records and confirm your reservation once the payment has been successfully verified.',
    isPublic: true,
  },

  // Expense
  {
    key: 'expense.requireReceiptAboveAmount',
    category: SettingCategory.EXPENSE,
    dataType: SettingDataType.NUMBER,
    description: 'Require receipt above amount',
    defaultValue: '0',
  },
  {
    key: 'expense.allowAdminCustomCategory',
    category: SettingCategory.EXPENSE,
    dataType: SettingDataType.BOOLEAN,
    description: 'Allow Admin to create custom categories',
    defaultValue: 'true',
  },
  {
    key: 'expense.allowReceptionistMinorEntry',
    category: SettingCategory.EXPENSE,
    dataType: SettingDataType.BOOLEAN,
    description: 'Allow Receptionist minor expense entry',
    defaultValue: 'true',
  },
  {
    key: 'expense.receptionistMinorLimit',
    category: SettingCategory.EXPENSE,
    dataType: SettingDataType.NUMBER,
    description: 'Receptionist minor expense limit',
    defaultValue: '5000',
  },
  {
    key: 'expense.finalizationRequired',
    category: SettingCategory.EXPENSE,
    dataType: SettingDataType.BOOLEAN,
    description: 'Expense finalization required',
    defaultValue: 'true',
  },

  // Security
  {
    key: 'security.sessionTimeoutMinutes',
    category: SettingCategory.SECURITY,
    dataType: SettingDataType.NUMBER,
    description: 'Session timeout in minutes',
    defaultValue: '480',
    isSensitive: true,
  },
  {
    key: 'security.passwordMinimumLength',
    category: SettingCategory.SECURITY,
    dataType: SettingDataType.NUMBER,
    description: 'Password minimum length',
    defaultValue: '8',
    isSensitive: true,
  },
  {
    key: 'security.requireUppercase',
    category: SettingCategory.SECURITY,
    dataType: SettingDataType.BOOLEAN,
    description: 'Require uppercase in password',
    defaultValue: 'true',
    isSensitive: true,
  },
  {
    key: 'security.requireLowercase',
    category: SettingCategory.SECURITY,
    dataType: SettingDataType.BOOLEAN,
    description: 'Require lowercase in password',
    defaultValue: 'true',
    isSensitive: true,
  },
  {
    key: 'security.requireNumber',
    category: SettingCategory.SECURITY,
    dataType: SettingDataType.BOOLEAN,
    description: 'Require number in password',
    defaultValue: 'true',
    isSensitive: true,
  },
  {
    key: 'security.requireSpecialCharacter',
    category: SettingCategory.SECURITY,
    dataType: SettingDataType.BOOLEAN,
    description: 'Require special character in password',
    defaultValue: 'true',
    isSensitive: true,
  },
  {
    key: 'security.maxFailedLoginAttempts',
    category: SettingCategory.SECURITY,
    dataType: SettingDataType.NUMBER,
    description: 'Maximum failed login attempts',
    defaultValue: '5',
    isSensitive: true,
  },
  {
    key: 'security.accountLockDurationMinutes',
    category: SettingCategory.SECURITY,
    dataType: SettingDataType.NUMBER,
    description: 'Account lock duration in minutes',
    defaultValue: '30',
    isSensitive: true,
  },
  {
    key: 'security.jwtExpiresIn',
    category: SettingCategory.SECURITY,
    dataType: SettingDataType.STRING,
    description: 'JWT access-token expiry',
    defaultValue: '1d',
    isSensitive: true,
  },
  {
    key: 'security.restrictInactiveLogin',
    category: SettingCategory.SECURITY,
    dataType: SettingDataType.BOOLEAN,
    description: 'Restrict inactive account login',
    defaultValue: 'true',
    isSensitive: true,
  },
  {
    key: 'security.forcePasswordChangeOnFirstLogin',
    category: SettingCategory.SECURITY,
    dataType: SettingDataType.BOOLEAN,
    description: 'Force password change on first login',
    defaultValue: 'false',
    isSensitive: true,
  },
  {
    key: 'security.enableTwoFactorFlag',
    category: SettingCategory.SECURITY,
    dataType: SettingDataType.BOOLEAN,
    description: 'Enable 2FA flag (future use)',
    defaultValue: 'false',
    isSensitive: true,
  },

  // Appearance
  {
    key: 'appearance.applicationName',
    category: SettingCategory.APPEARANCE,
    dataType: SettingDataType.STRING,
    description: 'Application display name',
    defaultValue: 'Hotel Residences POS',
    isPublic: true,
  },
  {
    key: 'appearance.primaryGold',
    category: SettingCategory.APPEARANCE,
    dataType: SettingDataType.COLOR,
    description: 'Primary gold shade',
    defaultValue: '#d4af37',
    isPublic: true,
  },
  {
    key: 'appearance.sidebarStyle',
    category: SettingCategory.APPEARANCE,
    dataType: SettingDataType.STRING,
    description: 'Sidebar style',
    defaultValue: 'expanded',
    isPublic: true,
  },
  {
    key: 'appearance.compactTableMode',
    category: SettingCategory.APPEARANCE,
    dataType: SettingDataType.BOOLEAN,
    description: 'Compact table mode',
    defaultValue: 'false',
    isPublic: true,
  },
  {
    key: 'appearance.defaultPageSize',
    category: SettingCategory.APPEARANCE,
    dataType: SettingDataType.NUMBER,
    description: 'Default table page size',
    defaultValue: '20',
    isPublic: true,
  },

  // System / maintenance / backup
  {
    key: 'system.maintenanceMode',
    category: SettingCategory.SYSTEM,
    dataType: SettingDataType.BOOLEAN,
    description: 'Maintenance mode enabled',
    defaultValue: 'false',
    isSensitive: true,
  },
  {
    key: 'system.maintenanceMessage',
    category: SettingCategory.SYSTEM,
    dataType: SettingDataType.STRING,
    description: 'Maintenance mode message',
    defaultValue: 'System is under maintenance. Please try again later.',
    isPublic: true,
  },
  {
    key: 'backup.autoEnabled',
    category: SettingCategory.SYSTEM,
    dataType: SettingDataType.BOOLEAN,
    description: 'Enable automatic scheduled backups',
    defaultValue: 'false',
    isSensitive: true,
  },
  {
    key: 'backup.retentionDays',
    category: SettingCategory.SYSTEM,
    dataType: SettingDataType.NUMBER,
    description: 'Backup retention days for cleanup',
    defaultValue: '30',
    isSensitive: true,
  },
  // Thermal receipt printer (direct Windows RAW print on reception PC)
  {
    key: 'hardware.receiptPrinterName',
    category: SettingCategory.SYSTEM,
    dataType: SettingDataType.STRING,
    description: 'Speed X SP 200 / POS-80 USB thermal receipt printer name',
    defaultValue: 'POS-80',
    isPublic: true,
  },
  {
    key: 'hardware.receiptPaperWidthMm',
    category: SettingCategory.SYSTEM,
    dataType: SettingDataType.NUMBER,
    description: 'Receipt paper width in millimeters',
    defaultValue: '80',
    isPublic: true,
  },
  {
    key: 'hardware.receiptPrintWidthMm',
    category: SettingCategory.SYSTEM,
    dataType: SettingDataType.NUMBER,
    description: 'Receipt printable width in millimeters',
    defaultValue: '72',
    isPublic: true,
  },
  {
    key: 'hardware.receiptAutoCut',
    category: SettingCategory.SYSTEM,
    dataType: SettingDataType.BOOLEAN,
    description: 'Enable partial auto-cut after printing',
    defaultValue: 'true',
    isPublic: true,
  },
];

export const SETTINGS_BY_KEY = new Map(
  SETTINGS_CATALOG.map((item) => [item.key, item]),
);

export const PUBLIC_SETTING_KEYS = SETTINGS_CATALOG.filter(
  (item) => item.isPublic,
).map((item) => item.key);

export const LEGACY_SETTING_ALIASES: Record<string, string> = {
  electricity_rate_per_unit: 'electricity.ratePerUnit',
  expense_approval_threshold: 'finance.expenseApprovalThreshold',
};
