import { BadRequestException, Injectable, Logger } from '@nestjs/common';
import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import type { AuthUser } from '../common/types/auth-user.type';
import type { ExportFormat, ReportPayload } from './report.types';

@Injectable()
export class ReportExportService {
  private readonly logger = new Logger(ReportExportService.name);

  async export(
    report: ReportPayload,
    format: ExportFormat,
    user: AuthUser,
  ): Promise<{ buffer: Buffer; contentType: string; filename: string }> {
    try {
      if (format === 'csv') {
        const buffer = Buffer.from(this.toCsv(report), 'utf8');
        this.logExport(report, format, user, true, report.rows.length);
        return {
          buffer,
          contentType: 'text/csv; charset=utf-8',
          filename: this.filename(report, 'csv'),
        };
      }
      if (format === 'xlsx') {
        const buffer = await this.toXlsx(report);
        this.logExport(report, format, user, true, report.rows.length);
        return {
          buffer,
          contentType:
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          filename: this.filename(report, 'xlsx'),
        };
      }
      if (format === 'pdf') {
        const buffer = await this.toPdf(report);
        this.logExport(report, format, user, true, report.rows.length);
        return {
          buffer,
          contentType: 'application/pdf',
          filename: this.filename(report, 'pdf'),
        };
      }
      throw new BadRequestException('Unsupported export format');
    } catch (error) {
      this.logExport(report, format, user, false, report.rows.length);
      if (error instanceof BadRequestException) throw error;
      throw new BadRequestException('Unable to generate export file');
    }
  }

  private filename(report: ReportPayload, ext: string) {
    const stamp = report.generatedAt.slice(0, 10);
    return `${report.reportType}-${stamp}.${ext}`;
  }

  private logExport(
    report: ReportPayload,
    format: ExportFormat,
    user: AuthUser,
    success: boolean,
    recordCount: number,
  ) {
    // No AuditLog model — application logger until a dedicated audit store exists.
    this.logger.log(
      JSON.stringify({
        event: 'REPORT_EXPORT',
        success,
        userId: user.id,
        fullName: user.fullName,
        role: user.role,
        reportType: report.reportType,
        format,
        filters: report.filters,
        recordCount,
        at: new Date().toISOString(),
      }),
    );
  }

  private toCsv(report: ReportPayload): string {
    const headers = report.columns.map((c) => c.header);
    const lines = [
      `"${report.reportName}"`,
      `"Generated At","${report.generatedAt}"`,
      `"Generated By","${report.generatedBy.fullName}"`,
      '',
      headers.map((h) => this.csvCell(h)).join(','),
      ...report.rows.map((row) =>
        report.columns
          .map((col) => this.csvCell(row[col.key]))
          .join(','),
      ),
    ];
    return lines.join('\n');
  }

  private csvCell(value: unknown): string {
    const text =
      value === null || value === undefined ? '' : String(value).replaceAll('"', '""');
    return `"${text}"`;
  }

  private async toXlsx(report: ReportPayload): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = report.generatedBy.fullName;
    workbook.created = new Date(report.generatedAt);

    const summarySheet = workbook.addWorksheet('Summary');
    summarySheet.addRow([report.reportName]);
    summarySheet.getRow(1).font = { bold: true, color: { argb: 'FFB8860B' } };
    summarySheet.addRow(['Generated At', report.generatedAt]);
    summarySheet.addRow(['Generated By', report.generatedBy.fullName]);
    summarySheet.addRow([]);
    summarySheet.addRow(['Summary']);
    Object.entries(report.summary).forEach(([key, value]) => {
      summarySheet.addRow([key, value ?? '']);
    });
    summarySheet.columns = [{ width: 28 }, { width: 28 }];

    const dataSheet = workbook.addWorksheet('Data');
    dataSheet.addRow(report.columns.map((c) => c.header));
    dataSheet.getRow(1).font = { bold: true };
    dataSheet.views = [{ state: 'frozen', ySplit: 1 }];
    report.rows.forEach((row) => {
      dataSheet.addRow(report.columns.map((col) => row[col.key] ?? ''));
    });
    if (Object.keys(report.totals).length > 0) {
      dataSheet.addRow([]);
      dataSheet.addRow(['Totals']);
      Object.entries(report.totals).forEach(([key, value]) => {
        dataSheet.addRow([key, value ?? '']);
      });
    }
    dataSheet.columns = report.columns.map(() => ({ width: 18 }));

    const arrayBuffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(arrayBuffer);
  }

  private async toPdf(report: ReportPayload): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc
        .fillColor('#111111')
        .fontSize(16)
        .text('Hotel Residences', { continued: false });
      doc
        .fillColor('#B8860B')
        .fontSize(14)
        .text(report.reportName, { underline: true });
      doc.moveDown(0.5);
      doc.fillColor('#333333').fontSize(9);
      doc.text(`Generated: ${report.generatedAt}`);
      doc.text(`Generated by: ${report.generatedBy.fullName}`);
      if (report.metadata?.confidential) {
        doc.fillColor('#B00020').text('CONFIDENTIAL');
      }
      doc.moveDown(0.5);
      doc.fillColor('#333333').text('Filters:');
      doc.text(JSON.stringify(report.filters));
      doc.moveDown(0.5);
      doc.text('Summary:');
      Object.entries(report.summary).forEach(([key, value]) => {
        doc.text(`${key}: ${value ?? '—'}`);
      });
      doc.moveDown(0.75);

      const colCount = Math.min(report.columns.length, 6);
      const usableWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
      const colWidth = usableWidth / colCount;
      const headers = report.columns.slice(0, colCount);

      doc.fillColor('#B8860B').fontSize(8);
      headers.forEach((col, index) => {
        doc.text(col.header, doc.page.margins.left + index * colWidth, doc.y, {
          width: colWidth - 4,
          continued: index < headers.length - 1,
        });
      });
      doc.text('');
      doc
        .moveTo(doc.page.margins.left, doc.y)
        .lineTo(doc.page.width - doc.page.margins.right, doc.y)
        .strokeColor('#B8860B')
        .stroke();
      doc.moveDown(0.3);

      doc.fillColor('#111111').fontSize(8);
      const maxRows = Math.min(report.rows.length, 40);
      for (let i = 0; i < maxRows; i += 1) {
        const row = report.rows[i];
        const y = doc.y;
        if (y > doc.page.height - 60) {
          doc.addPage();
        }
        headers.forEach((col, index) => {
          doc.text(
            String(row[col.key] ?? '—').slice(0, 28),
            doc.page.margins.left + index * colWidth,
            doc.y,
            {
              width: colWidth - 4,
              continued: index < headers.length - 1,
            },
          );
        });
        doc.text('');
      }
      if (report.rows.length > maxRows) {
        doc.moveDown(0.5);
        doc
          .fillColor('#666666')
          .text(
            `Showing first ${maxRows} of ${report.rows.length} rows. Use Excel/CSV for full export.`,
          );
      }

      const range = doc.bufferedPageRange();
      for (let i = 0; i < range.count; i += 1) {
        doc.switchToPage(i);
        doc
          .fontSize(8)
          .fillColor('#666666')
          .text(
            `Page ${i + 1} of ${range.count}`,
            40,
            doc.page.height - 30,
            { align: 'center' },
          );
      }

      doc.end();
    });
  }
}
